# Generated by Django 3.2.9 on 2021-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="licence",
            field=models.FileField(blank=True, null=True, upload_to="media/licenses"),
        ),
    ]
