# Generated by Django 3.2.9 on 2022-01-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20220102_1618"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientMedicalHistory",
        ),
    ]
