# Generated by Django 3.2.9 on 2022-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_patientmedicalhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
