# Generated by Django 3.2.9 on 2022-01-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_patientmedicalhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmedicalhistory",
            name="appointment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.appointment",
            ),
        ),
    ]
