# Generated by Django 3.2.9 on 2022-01-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_patientmedicalhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientMedicalHistory',
        ),
    ]
