# Generated by Django 3.2.9 on 2022-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_patientmedicalhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="fee",
            field=models.DecimalField(
                decimal_places=2, default="0.0", max_digits=8, null=True
            ),
        ),
    ]
