# Generated by Django 3.2.9 on 2022-01-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_speciality_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(max_length=200)),
                ('test_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(max_length=200)),
                ('payment_code', models.CharField(max_length=200, unique=True)),
                ('percentage_off_payment', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='fee',
            new_name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Follow Up'), ('D', 'Done')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.institution'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.doctor'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('test_done', models.BooleanField(default=False)),
                ('test_paid', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patient')),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentoption')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.availabletest')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentoption'),
        ),
    ]
